### ISSUE TITLE
Implement filter_distances()

### ISSUE THREAD

**Issue by shayne-andrews** [UBC-MDS/distrrr#14]
As a user, I want to know which point(s) are within a threshold distance to a target point based on a specified distance metric. These points should be returned as indices so I can access them from the dataframe in which they exist.

Acceptance Criteria

    * The function should return a vector of indices corresponding to observations that are within the given threshold distance to a specified observation

    * The function should return an unknown length vector of indices if the input dataframe

    * The function should throw error/exception for error parameters

**Comment by carrieklc** [comment]
Function implemented as of milestone 3. Closing issue.
