### ISSUE TITLE
create the vignette

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/distrrr#19]
Create a first vignette with `devtools::use_vignette("my-vignette")`

Write description of package with examples. 

[Example vignette, dplyr](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html)

[Unrendered version](https://github.com/tidyverse/dplyr/blob/master/vignettes/dplyr.Rmd)

**Comment by carrieklc** [comment]
Vignettes created in commit 995d9285cb8c6674152600b35a7f65958c94f6e0. Issue will be closed.
