### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/distrrr#9]
Great job on both the R and python packages!

You incorporated all the initial feedback and your tests are well done. 

- For your function descriptions: I understand that list in python and in R are different things, yet in your R description of the project you use lists continuously as inputs and outputs. I think you are referring to vectors in the R project, not necessarily lists. 

- You did great by setting up the package using the R package instructions. Here is some feedback so you can improve on that:
    - I found the license.md but I couldn't find the license created by R. 
    - Its confusing that you have a distrrr and distrr.Rcheck
    - Description, namespace, R and tests should be in the main directory (should have to go looking                around for them)
     - Namespace is not updated 

- In general the writing is very clear and everything is easy to understand. Here are some specific things you can improve:
    - For get_closest, the input is: “4 parameters: a dataframe, a list of numeric values k, int for number of neighbours…” and the output is “List of int (row indices) of length k”. I think you mean for the input: int for the number of neighbours k. 
    - In the get_distance function you have a misspelled function description, should be distance instead of distnace
    - In the test_get_distance, checker is misspelled. 

- You guys went above and beyond by setting up roxygen templates for your functions, here are some things you could improve:
    - Since you have multiple distance metrics, provide more information on the differences between these distance metrics, maybe provide a link (this should be present in all the functions that provide the option to select between multiple distances).
    - Its very confusing that fot get_all_distances the description says: Return distance/similarity metric for each row in a dataframe. Since all of the options are distances. 
    - The outputs in the empty functions are inconsistent. I.e. in get_distance you output -1 while in get_all_distances you output as.numeric(c()). 
    - There is no example in get_all_distances. 
    - The description of the parameters is inconsistent between functions. While get_all_distances says @param dist string..., filter_distances says: @param dist Char, type…
    - Get_closest, filtered_distances and get_distance don’t have a function description. 

- Finally your tests are well done and most of them test a good array of possible cases. You can improve your test cases:

Test_get_distance:
   - Only testing cases where input is numeric. It’s not testing whether the input is not numeric, or the type of metric is not a string. 
   - Should test that the output is the correct size and type 

Test_get_all_distances:
   - expect_error(get_all_distances("a",df), info = "first argument should be a vector").  “a” is a vector (a character vector)
   - Should test that the output is the correct size and type 

Test_get_closest:
   - Needs a test to check that the string input is a string and is one of your options. 

Test_filter_distances
   - Missing expect in the last test.

**Comment by EvanYathon** [comment]
I will take care of these:
* Namespace is not updated
* Its confusing that you have a distrrr and distrr.Rcheck
* Description, namespace, R and tests should be in the main directory (should have to go looking                around for them)

EDIT:  Fixed in [this PR](https://github.com/UBC-MDS/distrrr/pull/16).

**Comment by carrieklc** [comment]
Addressed the feedback above in commits throughout milestone 3 release. Closing issue. Thanks!
